highlighter: rouge

excerpt_separator: "\n\n"

paginate: 7
#paginate_path: "/blog/page:num/"

name: Developer Notebook
decription: "Ideas, Thoughts, Notes to self and mixed Ramblings and Rants"

#permalink: pretty

gems: [jekyll-paginate]

kramdown:
    input: GFM

 