highlighter: rouge

excerpt_separator: "\n\n\n"

paginate: 7

name: Developer Notebook
description: "Ideas, Thoughts, Notes to self and mixed Ramblings and Rants"

#permalink: pretty

gems: [jekyll-paginate]

kramdown:
    input: GFM

defaults:
    - 
      scope: 
        type: "posts"
      values:
        comments: true
        layout: "post"

 